language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: tiddlywiki ./*wiki --build

after_success: 
  - chmod +x travis/publish.sh
  - travis/publish.sh

branches:
  only:
    - master